/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs/new'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminTeamNewRouteImport } from './routes/admin/team/new'
import { Route as AdminBlogsEditIdRouteImport } from './routes/admin/blogs/edit/$id'
import { Route as AdminEventsEditIdRouteImport } from './routes/admin/events/edit/$id'
import { Route as AdminTeamEditIdRouteImport } from './routes/admin/team/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/admin/blogs/',
  path: '/admin/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/admin/blogs/new',
  path: '/admin/blogs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/admin/events/new',
  path: '/admin/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/admin/team/',
  path: '/admin/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamNewRoute = AdminTeamNewRouteImport.update({
  id: '/admin/team/new',
  path: '/admin/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsEditIdRoute = AdminBlogsEditIdRouteImport.update({
  id: '/admin/blogs/edit/$id',
  path: '/admin/blogs/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEditIdRoute = AdminEventsEditIdRouteImport.update({
  id: '/admin/events/edit/$id',
  path: '/admin/events/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamEditIdRoute = AdminTeamEditIdRouteImport.update({
  id: '/admin/team/edit/$id',
  path: '/admin/team/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/blogs/edit/$id': typeof AdminBlogsEditIdRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
  '/admin/team/edit/$id': typeof AdminTeamEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/blogs/edit/$id': typeof AdminBlogsEditIdRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
  '/admin/team/edit/$id': typeof AdminTeamEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/blogs/edit/$id': typeof AdminBlogsEditIdRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
  '/admin/team/edit/$id': typeof AdminTeamEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/team'
    | '/admin/login'
    | '/blogs/$slug'
    | '/admin/'
    | '/blogs/'
    | '/admin/blogs/new'
    | '/admin/events/new'
    | '/admin/team/new'
    | '/admin/blogs/'
    | '/admin/events/'
    | '/admin/team/'
    | '/admin/blogs/edit/$id'
    | '/admin/events/edit/$id'
    | '/admin/team/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/team'
    | '/admin/login'
    | '/blogs/$slug'
    | '/admin'
    | '/blogs'
    | '/admin/blogs/new'
    | '/admin/events/new'
    | '/admin/team/new'
    | '/admin/blogs'
    | '/admin/events'
    | '/admin/team'
    | '/admin/blogs/edit/$id'
    | '/admin/events/edit/$id'
    | '/admin/team/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/team'
    | '/admin/login'
    | '/blogs/$slug'
    | '/admin/'
    | '/blogs/'
    | '/admin/blogs/new'
    | '/admin/events/new'
    | '/admin/team/new'
    | '/admin/blogs/'
    | '/admin/events/'
    | '/admin/team/'
    | '/admin/blogs/edit/$id'
    | '/admin/events/edit/$id'
    | '/admin/team/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  InitiativesRoute: typeof InitiativesRoute
  TeamRoute: typeof TeamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminTeamNewRoute: typeof AdminTeamNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  AdminBlogsEditIdRoute: typeof AdminBlogsEditIdRoute
  AdminEventsEditIdRoute: typeof AdminEventsEditIdRoute
  AdminTeamEditIdRoute: typeof AdminTeamEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/admin/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/admin/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/admin/team'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/new': {
      id: '/admin/team/new'
      path: '/admin/team/new'
      fullPath: '/admin/team/new'
      preLoaderRoute: typeof AdminTeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs/edit/$id': {
      id: '/admin/blogs/edit/$id'
      path: '/admin/blogs/edit/$id'
      fullPath: '/admin/blogs/edit/$id'
      preLoaderRoute: typeof AdminBlogsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/edit/$id': {
      id: '/admin/events/edit/$id'
      path: '/admin/events/edit/$id'
      fullPath: '/admin/events/edit/$id'
      preLoaderRoute: typeof AdminEventsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team/edit/$id': {
      id: '/admin/team/edit/$id'
      path: '/admin/team/edit/$id'
      fullPath: '/admin/team/edit/$id'
      preLoaderRoute: typeof AdminTeamEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  InitiativesRoute: InitiativesRoute,
  TeamRoute: TeamRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminTeamNewRoute: AdminTeamNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  AdminBlogsEditIdRoute: AdminBlogsEditIdRoute,
  AdminEventsEditIdRoute: AdminEventsEditIdRoute,
  AdminTeamEditIdRoute: AdminTeamEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
